baseURL = 'https://joshuaisaact.github.io/Portfolio-Website/blog'
languageCode = 'en-gb'
title = 'Josh Development Blog'
theme = ""
publishDir = "../blog"

[params]
mainSections = ["posts"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

disableKinds = ["home"]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]
  taxonomy = ["HTML", "JSON"]
  taxonomyTerm = ["HTML", "JSON"]