baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'My Blog'
theme = ""

[params]
mainSections = ["posts"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true